from activations import *
from auxiliar import *
from backward import *
from dataset import *
from forward import *
from inference import *
from loss import *
from parameters import *
from tables import *
from verilog import *
